name: publish_and_notify

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ patst ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2.1.0

    # Runs a set of commands using the runners shell
    - name: Run the deploy process.
      run: |
        npm install
        tsc deploy.ts
        node deploy.js "${{ secrets.deploy_ftp_host }}" "${{ secrets.deploy_ftp_root }}" "${{ secrets.deploy_ftp_user }}" "${{ secrets.deploy_ftp_pass }}" "${{ secrets.slack_webhook_hash }}"